<template>
  <Navbar :categoryData="categories" />
  <div class="category">
    <CategoryList />
    <ProductList :products="filteredProducts" />
  </div>
  <Loading :isLoading="loading" />
</template>

<script setup lang="ts">
import { onMounted, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import CategoryList from '@/components/CategoryList.vue';
import Loading from '@/components/Loading.vue';
import Navbar from '@/components/Navbar.vue';
import ProductList from '@/components/ProductList.vue';
import { useCategoriesStore } from '@/stores/categories';
import { useProductsStore } from '@/stores/products';

const categoriesStore = useCategoriesStore()
const productsStore = useProductsStore()
const getProducts = productsStore.getProducts
const products = ref<any[]>([])
const filteredProducts = ref<any[]>([])
const route = useRoute()
const categoryId = ref()
const selectedCategory = ref()
const categories = ref<{ id: number; autogeneratedSlug: string; name: string; }[]>([]);
const loading = ref(true);

const getFilter = async (generalId: number, subId: any = null) => {
  filteredProducts.value = await products.value.filter((product: { categoryIds: number[]; }) => {
    if (generalId && subId) {
      return product.categoryIds.includes(subId);
    } else if (generalId) {
      return product.categoryIds.includes(generalId);
    } else if (subId) {
      return product.categoryIds.includes(subId);
    } else {
      return false; // Handle case where no IDs are provided
    }
  });
}
const getUpdateCategory = async () => {
  let regex = /-c(\d+)\//
  let match = route.fullPath.match(regex)

  await getProducts()
  products.value = await productsStore.products

  if (match) categoryId.value = +match[1]
  await categoriesStore.getCategory(categoryId.value)

  selectedCategory.value = categoriesStore.category
}
const savedCategory = ref<{ id: number; autogeneratedSlug: string; name: string; } | null>(null);

onMounted(async () => {
  await getUpdateCategory()

  getFilter(categoryId.value)

  // categories.value = [{ id: selectedCategory.value.id, autogeneratedSlug: selectedCategory.value.autogeneratedSlug, name: selectedCategory.value.name }]
  if (selectedCategory.value) {
    categories.value = [{
      id: selectedCategory.value.id,
      autogeneratedSlug: selectedCategory.value.autogeneratedSlug,
      name: selectedCategory.value.name
    }];
  }
  if (localStorage && localStorage.getItem('firstCategory') && localStorage.getItem('lastCategory')) {
    savedCategory.value = categories.value[0]


    const savedCategoryFromStorage: string | null = localStorage.getItem('firstCategory');
    const getSavedId: number = savedCategoryFromStorage !== null ? +savedCategoryFromStorage : 0;
    
    await categoriesStore.getCategory(getSavedId);
    categories.value = [categoriesStore.category]

    categories.value.push(({ id: savedCategory.value.id, autogeneratedSlug: savedCategory.value.autogeneratedSlug, name: savedCategory.value.name }))
  } else {
    localStorage.setItem('firstCategory', categoryId.value)
  }

  loading.value = false
})

watch(
  () => route.fullPath,
  async () => {
    loading.value = true
    await getUpdateCategory()

    if (selectedCategory.value.hasOwnProperty('parentId')) {
      localStorage.setItem('firstCategory', selectedCategory.value.parentId)
      localStorage.setItem('lastCategory', categoryId.value)

      getFilter(selectedCategory.value.parentId, categoryId.value)
      await categoriesStore.getCategory(categoryId.value)
      selectedCategory.value = categoriesStore.category
      categories.value.push({ id: selectedCategory.value.id, autogeneratedSlug: selectedCategory.value.autogeneratedSlug, name: selectedCategory.value.name })
    } else {
      localStorage.removeItem('lastCategory')
      getFilter(categoryId.value)
      categories.value.pop()
    }
    loading.value = false
  }
)
</script>
