<template>
  <nav>
    <router-link to="/">Магазин</router-link>
    <span v-for="category in categories" :key="category.id">
      <span> / </span>
      <router-link :to="`/category/${category.autogeneratedSlug}-c${category.id}/`">
        {{ category.name }}
      </router-link>
    </span>
  </nav>
</template>

<script setup lang="ts">
import { useLastProductStore } from '@/stores/lastProduct';
import { onMounted, ref, watch } from 'vue';
const categories = ref();
const hideProductRoute = ref(true)
const goToSavedProduct = ref('')
const lastProductStore = useLastProductStore()
const props = defineProps({
  categoryData: {
    type: Array,
    required: true,
  }
});

onMounted(() => {
  categories.value = props.categoryData;
  updateLastProduct()
})

const updateLastProduct = () => {
  if (lastProductStore.lastProduct) {
    goToSavedProduct.value = lastProductStore.lastProduct
    hideProductRoute.value = false
  }
}

watch(
  () => props.categoryData,
  (newValue) => {
    categories.value = newValue;
  }
)
</script>

<style lang="scss">
nav {
  padding: 0 30px 30px;

  a {
    font-weight: bold;
    color: #2c3e50;

    &.router-link-exact-active {
      color: #42b983;
      pointer-events: none;
    }
  }
}
</style>
