<template>
  <div class="productList">
    <transition-group name="product-list">
      <div class="productList__product product" v-for="product in products" :key="product?.id"
        @click="goToInfo(product?.autogeneratedSlug, product?.id)">
        <div class="product__imgWrapper">
          <img class="product__img" :src="product?.hdThumbnailUrl" alt="hdThumbnailUrl" />
        </div>
        <h2 class="product__name">
          {{ product?.name }}
        </h2>
        <p class="product__price">{{ product?.defaultDisplayedPriceFormatted }}</p>
        <button class="product__btn" @click="goToInfo(product?.autogeneratedSlug, product?.id)">
          Купить
        </button>
      </div>
    </transition-group>
  </div>
</template>
<script setup lang="ts">
import { useLastProductStore } from '@/stores/lastProduct';
import { useRouter } from 'vue-router';

interface Product {
  id: number
  hdThumbnailUrl: string
  name: string
  defaultDisplayedPriceFormatted: string
  autogeneratedSlug: string
}

const router = useRouter()
defineProps<{
  products: Product[]
}>()
const lastProductStore = useLastProductStore()
const goToInfo = (name: string, id: number) => {
  const newProduct = `product/${name}-p${id}/`
  lastProductStore.setLastProduct(newProduct)
  router.push({ name: 'ProductDetail', params: { name: name, id: id } })
}
</script>

<style scoped lang="scss">
.product-list-enter-active,
.product-list-leave-active {
  transition:
    opacity 0.5s,
    transform 0.5s;
}

.product-list-enter,
.product-list-leave-to {
  opacity: 0;
  transform: scale(0.8);
}

.productList {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: 10px;

  &__product {
    width: 100%;
    max-width: 260px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: space-between;
    gap: 10px;
    padding: 20px 10px;
    border-radius: 15px;
    cursor: pointer;
  }
}

.product {
  &__name {
    font-size: 16px;
    height: 30px;
  }

  &__imgWrapper {
    max-width: 250px;
    overflow: hidden;
    border-radius: 15px;
  }

  &__img {
    width: 100%;
    height: 100%;
    max-width: 100%;
    border-radius: 15px;
    transition: transform 0.3s ease;

    &:hover {
      transform: scale(1.2);
    }
  }

  &__price {
    font-weight: 800;
  }

  &__btn {
    display: inline-block;
    padding: 10px 20px;
    background-color: #007bff;
    color: white;
    border: none;
    border-radius: 5px;
    font-size: 16px;
    cursor: pointer;
    transition: background-color 0.3s ease;

    &:hover {
      background-color: #0056b3;
      animation: pulse 0.5s ease infinite alternate;
    }
  }
}

@keyframes pulse {
  0% {
    transform: scale(1);
  }

  100% {
    transform: scale(1.05);
  }
}
</style>
